version: "3.8"

services:
  oreilly-go:
    container_name: practice
    volumes:
      - .:/go/src/work
    working_dir: /go/src/work
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081